# Generated by Django 2.0 on 2018-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'Wait'), (2, 'Done'), (3, 'Partially done'), (4, 'Skipped')], default=1, max_length=1),
        ),
    ]
