# Generated by Django 2.0 on 2018-04-11 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180410_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 8, 36, 56, 220852)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'Wait'), (2, 'In progress'), (3, 'Done'), (4, 'Partially done'), (5, 'Skipped')], default=1, max_length=1),
        ),
    ]
