# Generated by Django 2.0 on 2018-04-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180411_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivity',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='to_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'Wait'), (3, 'Done')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='TaskActivity',
        ),
    ]
