# Generated by Django 2.0 on 2018-04-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180412_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
    ]
