# Generated by Django 2.0 on 2018-04-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(0, 'Wait'), (1, 'Done')], default=0, max_length=1),
        ),
    ]
