# Generated by Django 2.0 on 2018-04-15 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180413_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 15, 17, 22, 24, 659572)),
        ),
    ]
